server:
  port : 8080

spring :
  name : AutoNotification
  mail:
    host: smtp.gmail.com
    port: 587
    username: mohamedlabnine1@gmail.com
    password: tdmchmhqpxefkqaa
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka



