server :
  port : 8083

spring :
  application:
    name: autoSecurity



jwt:
  secret: MiAVzqUXy5Tfr1kVIGpPMiAVzqUXy5Tfr1kVIGpP5Tfr1kVIGpPMiAVzqUXy5Tfr1kVIGpPMiAVzqUXy5Tfr1kVIGpPMiAVzqUXy5Tfr1kVIGpP5Tfr1kVIGpPMiAVzqUXy5Tfr1kVIGpP
  expiration: 43200000
